spring.application.name=LeaveManagementSystem

# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/leave_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=your_username
spring.datasource.password=your_password


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



server.port=8080

logging.level.org.springframework.security=INFO
logging.level.com.example.leavemanagementsystem=INFO